version: 0.2

env:
  parameter-store:
    CONTENTFUL_ACCESS_TOKEN: "/E3N6JGP7XBGZ2F/CONTENTFUL_ACCESS_TOKEN"
    CONTENTFUL_ENVIRONMENT: "/E3N6JGP7XBGZ2F/CONTENTFUL_ENVIRONMENT"
    CONTENTFUL_SPACE: "/E3N6JGP7XBGZ2F/CONTENTFUL_SPACE"
    FEEDBACK_EMAIL: "/E3N6JGP7XBGZ2F/FEEDBACK_EMAIL"
    API_ENDPOINT: "/E3N6JGP7XBGZ2F/API_ENDPOINT"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Starting install - $(date)"
      - echo " $(date)"
      - echo "$(date)"
      

      - echo "Installing Node dependencies"
      - npm install

      - echo "Completed install - $(date)"
  pre_build:
    commands:
      - echo "Starting pre_build - $(date)"
    
      - echo "Linting Node source code"
      - npm run lint

      - echo "Testing Node source code"
      - npm test
      - echo "REACT_APP_CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE}\nREACT_APP_CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}\nREACT_APP_CONTENTFUL_ENVIRONMENT=${CONTENTFUL_ENVIRONMENT}\nREACT_APP_FEEDBACK_EMAIL=${FEEDBACK_EMAIL}\nREACT_APP_API_ENDPOINT=${API_ENDPOINT}" > .env
      - cat .env
      - echo "Completed pre_build - $(date)"
  build:
    commands:
      - echo "Starting build - $(date)"

      - npm run build

      - echo "Completed build - $(date)"
  post_build:
    commands:
      - echo "Starting post_build - $(date)"

      - export S3_BUCKET=$(aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query "Stacks[*].Outputs[?OutputKey=='WebBucket'].OutputValue" --output text)
      - bucket_path="s3://${S3_BUCKET}"
      - list_of_synced_files="files_synced.txt"
      - aws s3 sync build ${bucket_path} --delete --sse AES256 > ${list_of_synced_files}

      - export CLOUD_FRONT_ID=$(aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query "Stacks[*].Outputs[?OutputKey=='CloudFrontId'].OutputValue" --output text)
      - while read file; do file_list="$file_list ${file##*$bucket_path}"; done < ${list_of_synced_files}
      - aws cloudfront create-invalidation --distribution-id ${CLOUD_FRONT_ID} --paths ${file_list}
      - echo ${CLOUD_FRONT_ID}
      - echo "Completed post_build - $(date)"  
