AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: MDIDS IAM Roles and Policies
  
Resources:
  newIAMRoleAWS:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: AZ-IAM-Boundry
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              - lambda:List*
              - lambda:Get*
            Resource: "*"
          -
            Effect: Allow
            Action:
              - lambda:List*
              - lambda:Get*
              - lambda:InvokeFunction
            Resource:
              - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:edb_dataexplore_*
          -
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - "*"
