name: "Snyk"

on:
  push:
    branches: [ develop, master, qa ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop, master, qa ]
    
    
jobs:
  snyk_security:
    name: Snyk Security Check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      actions: write
      contents: read
      pull-requests: read
      security-events: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Open Source Dependency Security Check
        uses: snyk/actions/node@0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium --dev --sarif-file-output=snyk.sarif
          command: test

      - name: Checkout Enterprise GitHub Repository
        uses: actions/checkout@v2
        with:
          repository: EliLillyCo/.github
          ref: refs/heads/main
          token: ${{ secrets.GITHUBREADONLY }}
          persist-credentials: false
          path: ./enterprise-actions

      - name: Check Snyk Results File
        uses: ./enterprise-actions/actions/snyk-results-check
        with:
          file-path: ${{github.workspace}}/snyk.sarif
          severity-threshold: 'medium'