# Publish Github Workflows

name: Publish Github Artifacts

on:
  push:
    branches: [ master ]
    
jobs:
  
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
    
      - name: Step 1 -> Create a temporary artifacts download folder
        run: mkdir downloads
        
      - name: Step 2 -> Add Artifacts to publish to the folder
        run: |
          cd downloads
          echo 'alpha' > aplha.html
          echo 'bravo' > bravo.html
          echo 'charlie' > charlie.html
          cd ..
          
      - name: Step 3 -> Use the upload artifact github action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
    
